### ISSUE TITLE
急急急

### ISSUE THREAD

**Issue by xuligen** [UserAndy/wechatutils#5]
怎样才能把这个工程跑起来呢，必须搭建SVN服务器吗？可以导入eclipse在tomcat上跑吗？

**Comment by andyqian** [comment]
不需要搭建SVN服务器, 可以导入到eclipse中,但是不能tomcat下运行, 该项目的打包方式为jar,不可以直接在tomcat下运行, 你可以添加我的微信: Andyqian1994,

**Comment by xuligen** [comment]
能指导一下吗？

**Comment by andyqian** [comment]
你再加下微信，或者你留下你的微信，

**Comment by xuligen** [comment]
18383144229，谢谢
